version: "3"
services:
  8to6wav:
    container_name: 8to6wav
    build:
      context: .
      dockerfile: ./audioPipeline/8to6wav/Dockerfile
    networks:
        - red-internal
    external_links:
        - mmla-rabbitmq
    environment:
        - RABBITMQ_HOST=mmla-rabbitmq
  vad:
    container_name: vad
    build:
      context: .
      dockerfile: ./audioPipeline/vad/Dockerfile
    networks:
        - red-internal
    external_links:
        - mmla-rabbitmq
    environment:
        - RABBITMQ_HOST=mmla-rabbitmq

  doa:
    container_name: doa
    build:
      context: .
      dockerfile: ./audioPipeline/doa/Dockerfile
    networks:
        - red-internal
    external_links:
        - mmla-rabbitmq
    environment:
        - RABBITMQ_HOST=mmla-rabbitmq

  filter-doa:
    container_name: filter-doa
    build:
      context: .
      dockerfile: ./audioPipeline/filter-doa/Dockerfile
    networks:
        - red-internal
    external_links:
        - mmla-rabbitmq
    environment:
        - RABBITMQ_HOST=mmla-rabbitmq

  segmentator:
    container_name: segmentator
    build:
      context: .
      dockerfile: ./audioPipeline/segmentator/Dockerfile
    networks:
        - red-internal
    external_links:
        - mmla-rabbitmq
    environment:
        - RABBITMQ_HOST=mmla-rabbitmq

  transcriptor:
    container_name: transcriptor
    build:
      context: .
      dockerfile: ./audioPipeline/transcriptor/Dockerfile
    networks:
        - red-internal
    external_links:
        - mmla-rabbitmq
    environment:
        - RABBITMQ_HOST=mmla-rabbitmq

  nlp:
    container_name: nlp
    build:
      context: .
      dockerfile: ./audioPipeline/nlp/Dockerfile
    networks:
        - red-internal
    external_links:
        - mmla-rabbitmq
    environment:
        - RABBITMQ_HOST=mmla-rabbitmq

  apm:
    container_name: apm
    build:
      context: .
      dockerfile: ./audioPipeline/apm/Dockerfile
    networks:
        - red-internal
    external_links:
        - mmla-rabbitmq
    environment:
        - RABBITMQ_HOST=mmla-rabbitmq

networks:
  red-internal:
    external: 
      name: mmla-network
